# Generated by Django 3.1.2 on 2020-12-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201201_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlineclass',
            options={'verbose_name_plural': 'Order Line Classes'},
        ),
    ]
