# Generated by Django 3.1.2 on 2020-11-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructors',
            new_name='Instructor',
        ),
    ]
