# Generated by Django 3.1.2 on 2020-11-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20201106_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='category',
        ),
    ]
