# Generated by Django 3.1.2 on 2020-11-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_remove_instructor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='category',
            field=models.ManyToManyField(to='instructors.Category'),
        ),
    ]
