# Generated by Django 3.1.2 on 2020-11-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
