# Generated by Django 3.1.2 on 2020-11-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_class', '0003_auto_20201125_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25.99, max_digits=6),
            preserve_default=False,
        ),
    ]
