# Generated by Django 3.1.2 on 2020-11-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_class', '0004_workoutclass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutclass',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='workout_class.Equipment'),
        ),
    ]
