# Generated by Django 3.1.2 on 2020-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_class', '0005_auto_20201126_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
