# Generated by Django 3.1.2 on 2020-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_class', '0005_auto_20201128_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutclass',
            name='model_id',
            field=models.CharField(default='workout_class', editable=False, max_length=20),
        ),
    ]
