# Generated by Django 3.1.2 on 2020-11-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_class', '0007_auto_20201126_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_class.category'),
        ),
    ]
