# Generated by Django 3.1.2 on 2020-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_id',
            field=models.CharField(default='product', editable=False, max_length=20),
        ),
    ]
